name    'rocha-lcgdm'
version '0.0.3'
source 'UNKNOWN'
author 'LCGDM'
license 'Apache License, Version 2.0'
summary 'Package for managing lcgdm components'
description 'This package provides modules for managing lcgdm components'
project_page 'https://svnweb.cern.ch/trac/lcgdm'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'lcgdm/fetchcrl'
dependency 'puppetlabs/stdlib'
